tasks:
  - ssh-keys: null
  - install.ship_utilities:
  - rhceph_ansible: null
  - rgw-system-test:
      test: test_gc_list
      script: test_gc_list_verification.py
      clients: ['client.0']
      config:
          local_file_delete: true
          user_count: 1
          bucket_count: 2
          objects_count: 1000000
          gc_verification: true
          objects_size_range:
            min: 10
            max: 20
          test_ops:
            create_bucket: true
            create_object: true
            download_object: false
            delete_bucket_object: true
            sharding:
              enable: false
              max_shards: 0
            compression:
              enable: false
              type: zlib
